### ISSUE TITLE
one problem about deploying on nginx

### ISSUE THREAD

**Issue by b2r66sun** [akbaryahya/DockerGC#18]
Hi there, I wanna deploy dockergc on port 23336 and use nginx as reverse-proxy, but end up with login interface cannot respond, and no output in dockergc container. When I use ip address, it can login but cannot get into the game with error code 4206.

docker-compose and nginx config as follows, help!
```yaml
version: '3'
services:
  mongodb:
    restart: unless-stopped
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - /data/grasscutter/db:/data/db
  grasscutter:
    restart: unless-stopped
    container_name: dockergc
    image: siakbary/dockergc:ubuntu-dev-5.7
    command: -d 'mongodb://mongodb:27017' -f 'yes'
    volumes:
      - /data/grasscutter/resources:/home/Grasscutter/resources
    ports:
      - "22102:22102/udp"
      - "23336:443"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
```
```nginx
server{
    listen 443 ssl;
    server_name gc.<host>.com;
    ssl_certificate gc.<host>.com_bundle.crt;
    ssl_certificate_key gc.<host>.com.key;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
   
    location / {
	proxy_pass http://localhost:23336;
   }
}

server{
    listen 80;
    server_name gc.<host>.com;
    return 301 https://$host$request_uri;
}
```
