### ISSUE TITLE
White Screen!!!

### ISSUE THREAD

**Issue by 1995chen** [akbaryahya/DockerGC#28]
I deployed it in kubernetes, genshin.local.domain is a private domain name, I go to the DNS at home, and the following is the yaml file
我在kubernetes里面部署的，genshin.local.domain是私有域名，走的家里的DNS，下面是yaml文件

## Kubernetes Yaml
```
# doc: https://github.com/akbaryahya/DockerGC/blob/main/docker-compose.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genshin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genshin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genshin
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: genshin
    spec:
      restartPolicy: Always
      nodeName: centos-01
      volumes:
      - name: genshin
        persistentVolumeClaim:
          claimName: genshin

      containers:
      - name: mongodb
        imagePullPolicy: IfNotPresent
        image: mongo
        ports:
        - name: tcp-port
          containerPort: 27017
          protocol: TCP
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "nani"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "moemoekyu"
        volumeMounts:
        - mountPath: /data/db
          name: genshin
          subPath: db
      - name: genshin
        imagePullPolicy: IfNotPresent
        image: siakbary/dockergc:alpine-Patch-2.7-245e196
        stdin: true
        tty: true
        ports:
        - name: udp-port
          containerPort: 22102
          protocol: UDP
        - name: https-port
          containerPort: 443
          protocol: TCP
        - name: http-port
          containerPort: 80
          protocol: TCP
        args:
          - "-d"
          - "mongodb://nani:moemoekyu@127.0.0.1:27017"
          - "-b"
          - "genshin.local.domain"
          - "-g"
          - "0.0.0.0"
          - "-f"
          - "yes"
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
        - mountPath: /home/Grasscutter/resources
          name: genshin
          subPath: resources

---

apiVersion: v1
kind: Service
metadata:
  name: genshin
spec:
  ports:
  - port: 443
    targetPort: 443
    name: https-port
  - port: 80
    targetPort: 80
    name: http-port
  - port: 22102
    targetPort: 22102
    nodePort: 22102
    name: udp-port
    protocol: UDP
  selector:
    app: genshin
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: genshin.local.domain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass_request_headers on;
spec:
  rules:
  - host: genshin.local.domain
    http:
      paths:
      - backend:
          serviceName: genshin
          servicePort: 443
  tls:
  - hosts:
    - genshin.local.domain
    secretName: genshin

```

## Problems Encountered
![IMG_5387](https://user-images.githubusercontent.com/19407551/174285767-6d6a8406-e16e-4d11-a3e5-bfad5da99459.PNG)

Then i get white screen
![IMG_5388](https://user-images.githubusercontent.com/19407551/174285839-faa7369c-dbdf-4bd5-9b7d-fba921a4ac47.PNG)
Then timeout
![IMG_5389](https://user-images.githubusercontent.com/19407551/174286356-a3ffd020-07b9-45c9-8986-2b47a730d2a5.PNG)

no any log on the console....

```
19:01:44 <INFO:RegionHandler> [Dispatch] Client 192.168.0.55 request: query_region_list
>....
19:01:45 <INFO:Utils> https://genshin.local.domain/hk4e_global/mdk/shield/api/verify (V: 1.30.0) (OS: 15.4.1) (A:Yuanshen/379 CFNetwork/1331.0.7 Darwin/21.4.0)
>....
19:01:45 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] Client 192.168.0.55 logged in via token as 10002.
>....
19:01:45 <INFO:DispatchHandler> [Dispatch] Client 192.168.0.55 is trying to log in.
>....
19:01:45 <INFO:Utils> https://genshin.local.domain/hk4e_global/combo/granter/login/v2/login (V: 1.30.0) (OS: 15.4.1) (A:Yuanshen/379 CFNetwork/1331.0.7 Darwin/21.4.0)
>....
19:01:45 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] Client 192.168.0.55 succeed to exchange combo token.
>....
19:01:45 <INFO:DispatchHandler> [Dispatch] Client 192.168.0.55 is trying to log in.
>....
19:01:45 <INFO:RegionHandler> Client 192.168.0.55 (CNRELiOS2.7.0) (930af1f03222b44f) request: query_cur_region/os_usa
>....
19:01:45 <INFO:RegionHandler> https://genshin.local.domain/query_cur_region/os_usa?version=CNRELiOS2.7.0&lang=2&platform=1&binary=1&time=319&channel_id=1&sub_channel_id=0&account_type=1&dispatchSeed=930af1f03222b44f
```

----------------------------
/home # netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      204/java
udp        0      0 0.0.0.0:22102           0.0.0.0:*                           204/java

it seems that  22102 is not in listen state,what should i do next

i close firewalld in centos machine
